# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-9.3"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.provision "shell", inline: setup
  config.vm.provision "shell", inline: startup, run: "always", privileged: false
end

def setup
  <<~HEREDOC
    echo 'LC_ALL=en_US.UTF-8' >>/etc/default/locale
    apt install -y jupyter-notebook
  HEREDOC
end

def startup
  <<~HEREDOC
    nohup jupyter-notebook --ip 0.0.0.0 --port 8888 --no-browser --notebook-dir /vagrant >/dev/null 2>&1 &
  HEREDOC
end
