Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "setup", type: "shell", inline: setup
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777","fmode=666"]
  config.vm.hostname = "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end

def setup
	<<~HEREDOC
	# Fix broken resolv.conf
	rm /etc/resolv.conf
	ln -s /run/resolvconf/resolv.conf /etc/resolv.conf
	HEREDOC
end
